In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("googleplaystore.csv")

In [4]:
df.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [5]:
df.head(50)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
5,Paper flowers instructions,ART_AND_DESIGN,4.4,167,5.6M,"50,000+",Free,0,Everyone,Art & Design,"March 26, 2017",1.0,2.3 and up
6,Smoke Effect Photo Maker - Smoke Editor,ART_AND_DESIGN,3.8,178,19M,"50,000+",Free,0,Everyone,Art & Design,"April 26, 2018",1.1,4.0.3 and up
7,Infinite Painter,ART_AND_DESIGN,4.1,36815,29M,"1,000,000+",Free,0,Everyone,Art & Design,"June 14, 2018",6.1.61.1,4.2 and up
8,Garden Coloring Book,ART_AND_DESIGN,4.4,13791,33M,"1,000,000+",Free,0,Everyone,Art & Design,"September 20, 2017",2.9.2,3.0 and up
9,Kids Paint Free - Drawing Fun,ART_AND_DESIGN,4.7,121,3.1M,"10,000+",Free,0,Everyone,Art & Design;Creativity,"July 3, 2018",2.8,4.0.3 and up
10,Text on Photo - Fonteee,ART_AND_DESIGN,4.4,13880,28M,"1,000,000+",Free,0,Everyone,Art & Design,"October 27, 2017",1.0.4,4.1 and up
11,Name Art Photo Editor - Focus n Filters,ART_AND_DESIGN,4.4,8788,12M,"1,000,000+",Free,0,Everyone,Art & Design,"July 31, 2018",1.0.15,4.0 and up
12,Tattoo Name On My Photo Editor,ART_AND_DESIGN,4.2,44829,20M,"10,000,000+",Free,0,Teen,Art & Design,"April 2, 2018",3.8,4.1 and up
13,Mandala Coloring Book,ART_AND_DESIGN,4.6,4326,21M,"100,000+",Free,0,Everyone,Art & Design,"June 26, 2018",1.0.4,4.4 and up
14,3D Color Pixel by Number - Sandbox Art Coloring,ART_AND_DESIGN,4.4,1518,37M,"100,000+",Free,0,Everyone,Art & Design,"August 3, 2018",1.2.3,2.3 and up
15,Learn To Draw Kawaii Characters,ART_AND_DESIGN,3.2,55,2.7M,"5,000+",Free,0,Everyone,Art & Design,"June 6, 2018",NaN,4.2 and up
16,Photo Designer - Write your name with shapes,ART_AND_DESIGN,4.7,3632,5.5M,"500,000+",Free,0,Everyone,Art & Design,"July 31, 2018",3.1,4.1 and up
17,350 Diy Room Decor Ideas,ART_AND_DESIGN,4.5,27,17M,"10,000+",Free,0,Everyone,Art & Design,"November 7, 2017",1.0,2.3 and up
18,FlipaClip - Cartoon animation,ART_AND_DESIGN,4.3,194216,39M,"5,000,000+",Free,0,Everyone,Art & Design,"August 3, 2018",2.2.5,4.0.3 and up
19,ibis Paint X,ART_AND_DESIGN,4.6,224399,31M,"10,000,000+",Free,0,Everyone,Art & Design,"July 30, 2018",5.5.4,4.1 and up
20,Logo Maker - Small Business,ART_AND_DESIGN,4.0,450,14M,"100,000+",Free,0,Everyone,Art & Design,"April 20, 2018",4.0,4.1 and up
21,Boys Photo Editor - Six Pack & Men's Suit,ART_AND_DESIGN,4.1,654,12M,"100,000+",Free,0,Everyone,Art & Design,"March 20, 2018",1.1,4.0.3 and up
22,Superheroes Wallpapers | 4K Backgrounds,ART_AND_DESIGN,4.7,7699,4.2M,"500,000+",Free,0,Everyone 10+,Art & Design,"July 12, 2018",2.2.6.2,4.0.3 and up
23,Mcqueen Coloring pages,ART_AND_DESIGN,NaN,61,7.0M,"100,000+",Free,0,Everyone,Art & Design;Action & Adventure,"March 7, 2018",1.0.0,4.1 and up
24,HD Mickey Minnie Wallpapers,ART_AND_DESIGN,4.7,118,23M,"50,000+",Free,0,Everyone,Art & Design,"July 7, 2018",1.1.3,4.1 and up
25,Harley Quinn wallpapers HD,ART_AND_DESIGN,4.8,192,6.0M,"10,000+",Free,0,Everyone,Art & Design,"April 25, 2018",1.5,3.0 and up
26,Colorfit - Drawing & Coloring,ART_AND_DESIGN,4.7,20260,25M,"500,000+",Free,0,Everyone,Art & Design;Creativity,"October 11, 2017",1.0.8,4.0.3 and up
27,Animated Photo Editor,ART_AND_DESIGN,4.1,203,6.1M,"100,000+",Free,0,Everyone,Art & Design,"March 21, 2018",1.03,4.0.3 and up
28,Pencil Sketch Drawing,ART_AND_DESIGN,3.9,136,4.6M,"10,000+",Free,0,Everyone,Art & Design,"July 12, 2018",6.0,2.3 and up
29,Easy Realistic Drawing Tutorial,ART_AND_DESIGN,4.1,223,4.2M,"100,000+",Free,0,Everyone,Art & Design,"August 22, 2017",1.0,2.3 and up
30,Pink Silver Bow Keyboard Theme,ART_AND_DESIGN,4.2,1120,9.2M,"100,000+",Free,0,Everyone,Art & Design,"July 12, 2018",6.7.12.2018,4.0.3 and up
31,Art Drawing Ideas,ART_AND_DESIGN,4.1,227,5.2M,"50,000+",Free,0,Everyone,Art & Design,"May 31, 2018",1.2,2.3 and up
32,Anime Manga Coloring Book,ART_AND_DESIGN,4.5,5035,11M,"100,000+",Free,0,Everyone,Art & Design,"July 19, 2018",2.20,4.0 and up
33,Easy Origami Ideas,ART_AND_DESIGN,4.2,1015,11M,"100,000+",Free,0,Everyone,Art & Design,"January 6, 2018",1.1.0,4.1 and up
34,I Creative Idea,ART_AND_DESIGN,4.7,353,4.2M,"10,000+",Free,0,Teen,Art & Design,"April 27, 2018",1.6,4.1 and up
35,How to draw Ladybug and Cat Noir,ART_AND_DESIGN,3.8,564,9.2M,"100,000+",Free,0,Everyone,Art & Design,"July 11, 2018",2.1,4.1 and up
36,UNICORN - Color By Number & Pixel Art Coloring,ART_AND_DESIGN,4.7,8145,24M,"500,000+",Free,0,Everyone,Art & Design;Creativity,"August 2, 2018",1.0.9,4.4 and up
37,Floor Plan Creator,ART_AND_DESIGN,4.1,36639,Varies with device,"5,000,000+",Free,0,Everyone,Art & Design,"July 14, 2018",Varies with device,2.3.3 and up
38,PIP Camera - PIP Collage Maker,ART_AND_DESIGN,4.7,158,11M,"10,000+",Free,0,Everyone,Art & Design,"November 29, 2017",1.3,4.0.3 and up
39,How To Color Disney Princess - Coloring Pages,ART_AND_DESIGN,4.0,591,9.4M,"500,000+",Free,0,Everyone,Art & Design,"March 31, 2018",1,4.0 and up
40,Drawing Clothes Fashion Ideas,ART_AND_DESIGN,4.2,117,15M,"10,000+",Free,0,Everyone,Art & Design,"July 20, 2018",2.0.1,4.0.3 and up
41,Sad Poetry Photo Frames 2018,ART_AND_DESIGN,4.5,176,10M,"100,000+",Free,0,Everyone,Art & Design,"April 2, 2018",1.0,4.0.3 and up
42,Textgram - write on photos,ART_AND_DESIGN,4.4,295221,Varies with device,"10,000,000+",Free,0,Everyone,Art & Design,"July 30, 2018",Varies with device,Varies with device
43,Paint Splash!,ART_AND_DESIGN,3.8,2206,1.2M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"April 15, 2018",1.46,4.1 and up
44,Popsicle Sticks and Similar DIY Craft Ideas,ART_AND_DESIGN,4.2,26,12M,"10,000+",Free,0,Everyone,Art & Design,"January 3, 2018",1.0.0,4.1 and up
45,"Canva: Poster, banner, card maker & graphic de...",ART_AND_DESIGN,4.7,174531,24M,"10,000,000+",Free,0,Everyone,Art & Design,"July 31, 2018",1.6.1,4.1 and up
46,Install images with music to make video withou...,ART_AND_DESIGN,4.6,1070,26M,"100,000+",Free,0,Everyone,Art & Design,"November 14, 2017",1.6,4.1 and up
47,Little Teddy Bear Colouring Book Game,ART_AND_DESIGN,4.2,85,8.0M,"100,000+",Free,0,Everyone,Art & Design,"December 17, 2017",2.0.0,4.1 and up
48,How To Draw Food,ART_AND_DESIGN,4.3,845,7.9M,"100,000+",Free,0,Everyone,Art & Design,"May 28, 2018",1.0,2.3 and up
49,Monster Truck Stunt 3D 2019,AUTO_AND_VEHICLES,4.2,367,25M,"100,000+",Free,0,Everyone,Auto & Vehicles,"May 10, 2018",1.0,4.0.3 and up

In [6]:
ar=df[(df['Category']=='ART_AND_DESIGN')&(df['Rating'].isna())]                #age10=df[(df["Age"]<10)&(df["Age"]>5)]

In [7]:
df.loc[[23],'Rating']=3.9
df.loc[[7174],'Rating']=2.5
df.loc[[8871],'Rating']=0

In [8]:
df[(df['Category']=='ART_AND_DESIGN')&(df['Rating'])].isna()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6930,False,False,False,False,False,False,False,False,False,False,False,False,False
7174,False,False,False,False,False,False,False,False,False,False,False,False,False
8679,False,False,False,False,False,False,False,False,False,False,False,False,False
8712,False,False,False,False,False,False,False,False,False,False,False,False,False
8888,False,False,False,False,False,False,False,False,False,False,False,False,False

In [9]:
df[df['Type'].isnull()].index

Index([9148], dtype='int64')

In [10]:
df.loc[9148,"Type"]="Free"

In [11]:
df[df['Content Rating'].isnull()].index

Index([10472], dtype='int64')

In [12]:
df.loc[10472,:]

App               Life Made WI-Fi Touchscreen Photo Frame
Category                                              1.9
Rating                                               19.0
Reviews                                              3.0M
Size                                               1,000+
Installs                                             Free
Type                                                    0
Price                                            Everyone
Content Rating                                        NaN
Genres                                  February 11, 2018
Last Updated                                       1.0.19
Current Ver                                    4.0 and up
Android Ver                                           NaN
Name: 10472, dtype: object

In [13]:
df.loc[10472,'Content Rating']="Everyone"

In [14]:
df.isnull().sum()

App                  0
Category             0
Rating            1471
Reviews              0
Size                 0
Installs             0
Type                 0
Price                0
Content Rating       0
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [15]:
df[df["Current Ver"].isnull()].index

Index([15, 1553, 6322, 6803, 7333, 7407, 7730, 10342], dtype='int64')

In [16]:
df.loc[[15, 1553, 6322, 6803, 7333, 7407, 7730, 10342],:]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
15,Learn To Draw Kawaii Characters,ART_AND_DESIGN,3.2,55,2.7M,"5,000+",Free,0,Everyone,Art & Design,"June 6, 2018",NaN,4.2 and up
1553,Market Update Helper,LIBRARIES_AND_DEMO,4.1,20145,11k,"1,000,000+",Free,0,Everyone,Libraries & Demo,"February 12, 2013",NaN,1.5 and up
6322,Virtual DJ Sound Mixer,TOOLS,4.2,4010,8.7M,"500,000+",Free,0,Everyone,Tools,"May 10, 2017",NaN,4.0 and up
6803,BT Master,FAMILY,NaN,0,222k,100+,Free,0,Everyone,Education,"November 6, 2016",NaN,1.6 and up
7333,Dots puzzle,FAMILY,4.0,179,14M,"50,000+",Paid,$0.99,Everyone,Puzzle,"April 18, 2018",NaN,4.0 and up
7407,Calculate My IQ,FAMILY,NaN,44,7.2M,"10,000+",Free,0,Everyone,Entertainment,"April 3, 2017",NaN,2.3 and up
7730,UFO-CQ,TOOLS,NaN,1,237k,10+,Paid,$0.99,Everyone,Tools,"July 4, 2016",NaN,2.0 and up
10342,La Fe de Jesus,BOOKS_AND_REFERENCE,NaN,8,658k,"1,000+",Free,0,Everyone,Books & Reference,"January 31, 2017",NaN,3.0 and up

In [17]:
ver=df['Current Ver'].mode()
df[df['Current Ver'].isnull()].index
ver

0    Varies with device
Name: Current Ver, dtype: object

In [18]:
df.loc[[15, 1553, 6322, 6803, 7333, 7407, 7730, 10342],'Current Ver']='Varies with device'

In [19]:
tu=df[df["Android Ver"].isnull()].index

In [20]:
df.loc[tu,:] ='4.0 and above'

C:\Users\user\AppData\Local\Temp\ipykernel_11804\1434401147.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '4.0 and above' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[tu,:] ='4.0 and above'

In [21]:
art=df[(df['Category']=='ART_AND_DESIGN')]

In [22]:
df["Category"].unique()

array(['ART_AND_DESIGN', 'AUTO_AND_VEHICLES', 'BEAUTY',
       'BOOKS_AND_REFERENCE', 'BUSINESS', 'COMICS', 'COMMUNICATION',
       'DATING', 'EDUCATION', 'ENTERTAINMENT', 'EVENTS', 'FINANCE',
       'FOOD_AND_DRINK', 'HEALTH_AND_FITNESS', 'HOUSE_AND_HOME',
       'LIBRARIES_AND_DEMO', 'LIFESTYLE', 'GAME', 'FAMILY', 'MEDICAL',
       'SOCIAL', 'SHOPPING', 'PHOTOGRAPHY', 'SPORTS', 'TRAVEL_AND_LOCAL',
       'TOOLS', 'PERSONALIZATION', 'PRODUCTIVITY', 'PARENTING', 'WEATHER',
       'VIDEO_PLAYERS', 'NEWS_AND_MAGAZINES', 'MAPS_AND_NAVIGATION',
       '4.0 and above'], dtype=object)

In [23]:
rval=df[df['Category']=='AUTO_AND_VEHICLES']['Rating'].median()

In [24]:
df[df['Category']=='AUTO_AND_VEHICLES']["Rating"].isnull().index

Index([   49,    50,    51,    52,    53,    54,    55,    56,    57,    58,
          59,    60,    61,    62,    63,    64,    65,    66,    67,    68,
          69,    70,    71,    72,    73,    74,    75,    76,    77,    78,
          79,    80,    81,    82,    83,    84,    85,    86,    87,    88,
          89,    90,    91,    92,    93,    94,    95,    96,    97,  4120,
        4216,  4376,  4622,  4697,  5015,  5023,  5101,  5247,  5310,  6129,
        6151,  6160,  6226,  6245,  6468,  7183,  7341,  7419,  7511,  7790,
        7801,  8289,  8866,  8934,  9713,  9951,  9956,  9959,  9964, 10130,
       10137, 10345, 10486, 10764, 10811],
      dtype='int64')

In [25]:
df.loc[[   49,    50,    51,    52,    53,    54,    55,    56,    57,    58,
          59,    60,    61,    62,    63,    64,    65,    66,    67,    68,
          69,    70,    71,    72,    73,    74,    75,    76,    77,    78,
          79,    80,    81,    82,    83,    84,    85,    86,    87,    88,
          89,    90,    91,    92,    93,    94,    95,    96,    97,  4120,
        4216,  4376,  4622,  4697,  5015,  5023,  5101,  5247,  5310,  6129,
        6151,  6160,  6226,  6245,  6468,  7183,  7341,  7419,  7511,  7790,
        7801,  8289,  8866,  8934,  9713,  9951,  9956,  9959,  9964, 10130,
       10137, 10345, 10486, 10764, 10811],['Rating']]=rval

In [26]:
df[df['Category']=='BEAUTY']["Rating"].isnull().index

Index([   98,    99,   100,   101,   102,   103,   104,   105,   106,   107,
         108,   109,   110,   111,   112,   113,   114,   115,   116,   117,
         118,   119,   120,   121,   122,   123,   124,   125,   126,   127,
         128,   129,   130,   131,   132,   133,   134,   135,   136,   137,
         138,  5192,  5998,  6222,  6318,  6506,  6828,  7021,  7460,  8505,
        9205, 10022, 10289],
      dtype='int64')

In [27]:
bval=df[df['Category']=='BEAUTY']['Rating'].median()

In [28]:
df.loc[[   98,    99,   100,   101,   102,   103,   104,   105,   106,   107,
         108,   109,   110,   111,   112,   113,   114,   115,   116,   117,
         118,   119,   120,   121,   122,   123,   124,   125,   126,   127,
         128,   129,   130,   131,   132,   133,   134,   135,   136,   137,
         138,  5192,  5998,  6222,  6318,  6506,  6828,  7021,  7460,  8505,
        9205, 10022, 10289],['Rating']]=bval

In [29]:
bu=df[df['Category']=='BOOKS_AND_REFERENCE']["Rating"].isnull().index

In [30]:
br=df[df['Category']=='BOOKS_AND_REFERENCE']["Rating"].median()

In [31]:
df.loc[bu,'Rating']=br

In [32]:
bs=df[df['Category']=='BUSINESS']["Rating"].isnull().index

In [33]:
bsm=df[df['Category']=='BUSINESS']["Rating"].median()

In [34]:
df.loc[bs,'Rating']=bsm

In [35]:
co=df[df['Category']=='COMICS']["Rating"].isnull().index

In [36]:
com=df[df['Category']=='COMICS']["Rating"].median()

In [37]:
df.loc[co,'Rating']=com

In [38]:
cm=df[df['Category']=='COMMUNICATION']["Rating"].isnull().index

In [39]:
cmm=df[df['Category']=='COMMUNICATION']["Rating"].median()

In [40]:
df.loc[cm,'Rating']=cmm

In [41]:
da=df[df['Category']=='DATING']["Rating"].isnull().index

In [42]:
dat=df[df['Category']=='DATING']["Rating"].median()

In [43]:
df.loc[da,["Rating"]]=dat

In [44]:
ed=df[df['Category']=='EDUCATION']["Rating"].isnull().index
ed

Index([699, 700, 701, 702, 703, 704, 705, 706, 707, 708,
       ...
       845, 846, 847, 848, 849, 850, 851, 852, 853, 854],
      dtype='int64', length=156)

In [45]:
edu=df[df['Category']=='EDUCATION']["Rating"].median()

In [46]:
df.loc[ed,'Rating']=edu

In [47]:
en=df[df['Category']=='ENTERTAINMENT']["Rating"].isnull().index

In [48]:
ent=df[df['Category']=='ENTERTAINMENT']["Rating"].median()

In [49]:
df.loc[en,'Rating']=ent

In [50]:
ev=df[df['Category']=='EVENTS']["Rating"].isnull().index

In [51]:
evt=df[df['Category']=='EVENTS']["Rating"].median()

In [52]:
df.loc[ev,'Rating']=evt

In [53]:
fi=df[df['Category']=='FINANCE']["Rating"].isnull().index

In [54]:
fin=df[df['Category']=='FINANCE']["Rating"].median()

In [55]:
df.loc[fi,'Rating']=fin

In [56]:
fo=df[df['Category']=='FOOD_AND_DRINK']["Rating"].isnull().index
foo=df[df['Category']=='FOOD_AND_DRINK']["Rating"].median()
df.loc[fo,'Rating']=foo

In [57]:
ho=df[df['Category']=='HOUSE_AND_HOME']["Rating"].isnull().index
hou=df[df['Category']=='HOUSE_AND_HOME']["Rating"].median()
df.loc[ho,'Rating']=hou

In [58]:
he=df[df['Category']=='HEALTH_AND_FITNESS']["Rating"].isnull().index
hel=df[df['Category']=='HEALTH_AND_FITNESS']["Rating"].median()
df.loc[he,'Rating']=hel

In [59]:
li=df[df['Category']=='LIBRARIES_AND_DEMO']["Rating"].isnull().index
lib=df[df['Category']=='LIBRARIES_AND_DEMO']["Rating"].median()
df.loc[li,'Rating']=lib

In [60]:
lif=df[df['Category']=='LIFESTYLE']["Rating"].isnull().index
life=df[df['Category']=='LIFESTYLE']["Rating"].median()
df.loc[lif,'Rating']=life

In [61]:
ga=df[df['Category']=='GAME']["Rating"].isnull().index
game=df[df['Category']=='GAME']["Rating"].median()
df.loc[ga,'Rating']=game

In [62]:
fa=df[df['Category']=='FAMILY']["Rating"].isnull().index
fam=df[df['Category']=='FAMILY']["Rating"].median()
df.loc[fa,'Rating']=fam

In [63]:
me=df[df['Category']=='MEDICAL']["Rating"].isnull().index
med=df[df['Category']=='MEDICAL']["Rating"].median()
df.loc[me,'Rating']=med

In [64]:
so=df[df['Category']=='SOCIAL']["Rating"].isnull().index
soc=df[df['Category']=='SOCIAL']["Rating"].median()
df.loc[so,'Rating']=soc

In [65]:
sho=df[df['Category']=='SHOPPING']["Rating"].isnull().index
shoc=df[df['Category']=='SHOPPING']["Rating"].median()
df.loc[sho,'Rating']=shoc

In [66]:
po=df[df['Category']=='PHOTOGRAPHY']["Rating"].isnull().index
pho=df[df['Category']=='PHOTOGRAPHY']["Rating"].median()
df.loc[po,'Rating']=pho

In [67]:
spo=df[df['Category']=='SPORTS']["Rating"].isnull().index
spoo=df[df['Category']=='SPORTS']["Rating"].median()
df.loc[spo,'Rating']=spoo

In [68]:
tro=df[df['Category']=='TRAVEL_AND_LOCAL']["Rating"].isnull().index
troo=df[df['Category']=='TRAVEL_AND_LOCAL']["Rating"].median()
df.loc[tro,'Rating']=troo

In [69]:
tol=df[df['Category']=='TOOLS']["Rating"].isnull().index
tool=df[df['Category']=='TOOLS']["Rating"].median()
df.loc[tol,'Rating']=tool

In [70]:
pe=df[df['Category']=='PERSONALIZATION']["Rating"].isnull().index
per=df[df['Category']=='PERSONALIZATION']["Rating"].median()
df.loc[pe,'Rating']=per

In [71]:
pro=df[df['Category']=='PRODUCTIVITY']["Rating"].isnull().index
prod=df[df['Category']=='PRODUCTIVITY']["Rating"].median()
df.loc[pro,'Rating']=prod

In [72]:
par=df[df['Category']=='PARENTING']["Rating"].isnull().index
pare=df[df['Category']=='PARENTING']["Rating"].median()
df.loc[par,'Rating']=pare

In [73]:
whe=df[df['Category']=='WEATHER']["Rating"].isnull().index
whee=df[df['Category']=='WEATHER']["Rating"].median()
df.loc[whe,'Rating']=whee

In [74]:
vi=df[df['Category']=='VIDEO_PLAYERS']["Rating"].isnull().index
vid=df[df['Category']=='VIDEO_PLAYERS']["Rating"].median()
df.loc[vi,'Rating']=vid

In [75]:
new=df[df['Category']=='NEWS_AND_MAGAZINES']["Rating"].isnull().index
news=df[df['Category']=='NEWS_AND_MAGAZINES']["Rating"].median()
df.loc[new,'Rating']=news

In [76]:
map=df[df['Category']=='MAPS_AND_NAVIGATION']["Rating"].isnull().index
maps=df[df['Category']=='MAPS_AND_NAVIGATION']["Rating"].median()
df.loc[map,'Rating']=maps

In [77]:
df.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      0
Current Ver       0
Android Ver       0
dtype: int64