In [1]:
import pandas as pd

In [2]:
import plotly.express as px

In [3]:
# !pip install plotly

In [4]:
df= px.data.iris()
df.head()

   sepal_length  sepal_width  petal_length  petal_width species  species_id
0           5.1          3.5           1.4          0.2  setosa           1
1           4.9          3.0           1.4          0.2  setosa           1
2           4.7          3.2           1.3          0.2  setosa           1
3           4.6          3.1           1.5          0.2  setosa           1
4           5.0          3.6           1.4          0.2  setosa           1

In [5]:
px.scatter(data_frame=df, x='sepal_length', y='petal_length', color='species', size='petal_width')

In [6]:
df1= pd.DataFrame([12,14,15,17,18,20,22,74])
df1.describe()

               0
count   8.000000
mean   24.000000
std    20.459018
min    12.000000
25%    14.750000
50%    17.500000
75%    20.500000
max    74.000000

In [7]:
# box plot -outlier find krrna
px.box(df1)