In [1]:
import pandas as pd
df= pd.read_csv('2023_Countries by Population.csv')
df.head()

,place,pop1980,pop2000,pop2010,pop2022,pop2023,pop2030,pop2050,country,area,landAreaKm,cca2,cca3,netChange,growthRate,worldPercentage,density,densityMi,rank
0,356,696828385.0,1.059634e+09,1.240614e+09,1.417173e+09,1.428628e+09,1.514994e+09,1.670491e+09,India,3287590.0,2973190.0,IN,IND,0.4184,0.0081,0.1785,480.5033,1244.5036,1
1,156,982372466.0,1.264099e+09,1.348191e+09,1.425887e+09,1.425671e+09,1.415606e+09,1.312636e+09,China,9706961.0,9424702.9,CN,CHN,-0.0113,-0.0002,0.1781,151.2696,391.7884,2
2,840,223140018.0,2.823986e+08,3.111828e+08,3.382899e+08,3.399966e+08,3.521623e+08,3.753920e+08,United States,9372610.0,9147420.0,US,USA,0.0581,0.0050,0.0425,37.1686,96.2666,3
3,360,148177096.0,2.140724e+08,2.440162e+08,2.755013e+08,2.775341e+08,2.921501e+08,3.172252e+08,Indonesia,1904569.0,1877519.0,ID,IDN,0.0727,0.0074,0.0347,147.8196,382.8528,4
4,586,80624057.0,1.543699e+08,1.944545e+08,2.358249e+08,2.404857e+08,2.740298e+08,3.678085e+08,Pakistan,881912.0,770880.0,PK,PAK,0.1495,0.0198,0.0300,311.9625,807.9829,5

In [2]:
df= pd.read_csv('2023_Countries by Population.csv')
df.head()

,place,pop1980,pop2000,pop2010,pop2022,pop2023,pop2030,pop2050,country,area,landAreaKm,cca2,cca3,netChange,growthRate,worldPercentage,density,densityMi,rank
0,356,696828385.0,1.059634e+09,1.240614e+09,1.417173e+09,1.428628e+09,1.514994e+09,1.670491e+09,India,3287590.0,2973190.0,IN,IND,0.4184,0.0081,0.1785,480.5033,1244.5036,1
1,156,982372466.0,1.264099e+09,1.348191e+09,1.425887e+09,1.425671e+09,1.415606e+09,1.312636e+09,China,9706961.0,9424702.9,CN,CHN,-0.0113,-0.0002,0.1781,151.2696,391.7884,2
2,840,223140018.0,2.823986e+08,3.111828e+08,3.382899e+08,3.399966e+08,3.521623e+08,3.753920e+08,United States,9372610.0,9147420.0,US,USA,0.0581,0.0050,0.0425,37.1686,96.2666,3
3,360,148177096.0,2.140724e+08,2.440162e+08,2.755013e+08,2.775341e+08,2.921501e+08,3.172252e+08,Indonesia,1904569.0,1877519.0,ID,IDN,0.0727,0.0074,0.0347,147.8196,382.8528,4
4,586,80624057.0,1.543699e+08,1.944545e+08,2.358249e+08,2.404857e+08,2.740298e+08,3.678085e+08,Pakistan,881912.0,770880.0,PK,PAK,0.1495,0.0198,0.0300,311.9625,807.9829,5

In [3]:
df.columns

Index(['place', 'pop1980', 'pop2000', 'pop2010', 'pop2022', 'pop2023',
       'pop2030', 'pop2050', 'country', 'area', 'landAreaKm', 'cca2', 'cca3',
       'netChange', 'growthRate', 'worldPercentage', 'density', 'densityMi',
       'rank'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   place            234 non-null    int64
 1   pop1980          234 non-null    float64
 2   pop2000          234 non-null    float64
 3   pop2010          234 non-null    float64
 4   pop2022          234 non-null    float64
 5   pop2023          234 non-null    float64
 6   pop2030          234 non-null    float64
 7   pop2050          234 non-null    float64
 8   country          234 non-null    object
 9   area             234 non-null    float64
 10  landAreaKm       234 non-null    float64
 11  cca2             233 non-null    object
 12  cca3             234 non-null    object
 13  netChange        226 non-null    float64
 14  growthRate       234 non-null    float64
 15  worldPercentage  228 non-null    float64
 16  density          234 non-null    float64
 17  densityMi        234 non-null    float64
 18  rank             234 non-null    int64
dtypes: float64(14), int64(2), object(3)
memory usage: 34.9+ KB

In [5]:
df.isnull().sum()

place              0
pop1980            0
pop2000            0
pop2010            0
pop2022            0
pop2023            0
pop2030            0
pop2050            0
country            0
area               0
landAreaKm         0
cca2               1
cca3               0
netChange          8
growthRate         0
worldPercentage    6
density            0
densityMi          0
rank               0
dtype: int64

In [6]:
# to find population of 2025

oneyear= df.loc[:,'pop2023']*df.loc[:,'growthRate']
two=oneyear*2
two

0      2.314377e+07
1     -5.702685e+05
2      3.399966e+06
3      4.107505e+06
4      9.523232e+06
           ...
229   -7.894800e+00
230    2.198780e+01
231    1.935000e+00
232    4.467480e+01
233    1.626520e+01
Length: 234, dtype: float64

In [7]:
df.loc[:,'pop2023']+two

0      1.451771e+09
1      1.425101e+09
2      3.433965e+08
3      2.816416e+08
4      2.500089e+08
           ...
229    4.378105e+03
230    3.812988e+03
231    1.936935e+03
232    1.937675e+03
233    5.342652e+02
Length: 234, dtype: float64

In [8]:
df.insert(loc=6,column='pop2025', value=df.loc[:,'pop2023']+two)

In [9]:
df.head(10)

,place,pop1980,pop2000,pop2010,pop2022,pop2023,pop2025,pop2030,pop2050,country,area,landAreaKm,cca2,cca3,netChange,growthRate,worldPercentage,density,densityMi,rank
0,356,696828385.0,1.059634e+09,1.240614e+09,1.417173e+09,1.428628e+09,1.451771e+09,1.514994e+09,1.670491e+09,India,3287590.0,2973190.0,IN,IND,0.4184,0.0081,0.1785,480.5033,1244.5036,1
1,156,982372466.0,1.264099e+09,1.348191e+09,1.425887e+09,1.425671e+09,1.425101e+09,1.415606e+09,1.312636e+09,China,9706961.0,9424702.9,CN,CHN,-0.0113,-0.0002,0.1781,151.2696,391.7884,2
2,840,223140018.0,2.823986e+08,3.111828e+08,3.382899e+08,3.399966e+08,3.433965e+08,3.521623e+08,3.753920e+08,United States,9372610.0,9147420.0,US,USA,0.0581,0.0050,0.0425,37.1686,96.2666,3
3,360,148177096.0,2.140724e+08,2.440162e+08,2.755013e+08,2.775341e+08,2.816416e+08,2.921501e+08,3.172252e+08,Indonesia,1904569.0,1877519.0,ID,IDN,0.0727,0.0074,0.0347,147.8196,382.8528,4
4,586,80624057.0,1.543699e+08,1.944545e+08,2.358249e+08,2.404857e+08,2.500089e+08,2.740298e+08,3.678085e+08,Pakistan,881912.0,770880.0,PK,PAK,0.1495,0.0198,0.0300,311.9625,807.9829,5
5,566,72951439.0,1.228520e+08,1.609529e+08,2.185412e+08,2.238046e+08,2.345920e+08,2.625804e+08,3.774599e+08,Nigeria,923768.0,910770.0,NG,NGA,0.1680,0.0241,0.0280,245.7312,636.4439,6
6,76,122288383.0,1.758737e+08,1.963535e+08,2.153135e+08,2.164224e+08,2.186732e+08,2.239090e+08,2.308857e+08,Brazil,8515767.0,8358140.0,BR,BRA,0.0393,0.0052,0.0270,25.8936,67.0645,7
7,50,83929765.0,1.291933e+08,1.483911e+08,1.711864e+08,1.729543e+08,1.765172e+08,1.844241e+08,2.039049e+08,Bangladesh,147570.0,130170.0,BD,BGD,0.0557,0.0103,0.0216,1328.6803,3441.2821,8
8,643,138257420.0,1.468448e+08,1.432426e+08,1.447133e+08,1.444444e+08,1.438955e+08,1.414327e+08,1.331330e+08,Russia,17098242.0,16376870.0,RU,RUS,-0.0158,-0.0019,0.0180,8.8200,22.8439,9
9,484,67705186.0,9.787344e+07,1.125324e+08,1.275041e+08,1.284556e+08,1.303824e+08,1.345341e+08,1.437724e+08,Mexico,1964375.0,1943950.0,MX,MEX,0.0299,0.0075,0.0160,66.0797,171.1463,10

In [10]:
# df.loc[:,'pop2023']-oneyear

In [11]:
df[df.loc[:,'worldPercentage'].isnull()]

,place,pop1980,pop2000,pop2010,pop2022,pop2023,pop2025,pop2030,pop2050,country,area,landAreaKm,cca2,cca3,netChange,growthRate,worldPercentage,density,densityMi,rank
228,666,6106.0,6274.0,6052.0,5862.0,5840.0,5795.6160,5651.0,5165.0,Saint Pierre and Miquelon,242.00,242.00,PM,SPM,NaN,-0.0038,NaN,24.1322,62.5025,229
229,500,11452.0,5138.0,4938.0,4390.0,4386.0,4378.1052,4301.0,3781.0,Montserrat,102.00,102.00,MS,MSR,NaN,-0.0009,NaN,43.0000,111.3700,230
230,238,2240.0,3080.0,3187.0,3780.0,3791.0,3812.9878,3869.0,3779.0,Falkland Islands,12173.00,12173.00,FK,FLK,NaN,0.0029,NaN,0.3114,0.8066,231
231,570,3637.0,2074.0,1812.0,1934.0,1935.0,1936.9350,1948.0,2096.0,Niue,261.00,261.00,NU,NIU,0.0,0.0005,NaN,7.4138,19.2017,232
232,772,1647.0,1666.0,1367.0,1871.0,1893.0,1937.6748,2046.0,2430.0,Tokelau,12.00,10.00,TK,TKL,NaN,0.0118,NaN,189.3000,490.2870,233
233,336,733.0,651.0,596.0,510.0,518.0,534.2652,561.0,731.0,Vatican City,0.44,0.44,VA,VAT,NaN,0.0157,NaN,1177.2727,3049.1364,234

In [12]:
df.loc[:,'pop2023'].sum()

np.float64(8043615390.0)

In [13]:
df.loc[0,'pop2023']

np.float64(1428627663.0)

In [14]:
(1428627663/8043615390)

0.177610140929426

In [15]:
null_index= df[df.loc[:,'worldPercentage'].isnull()].index

In [16]:
null_index

Index([228, 229, 230, 231, 232, 233], dtype='int64')

In [17]:
values = df.loc[null_index,'pop2023']/df.loc[:,'pop2023'].sum()

In [18]:
values

228    7.260417e-07
229    5.452772e-07
230    4.713055e-07
231    2.405635e-07
232    2.353419e-07
233    6.439890e-08
Name: pop2023, dtype: float64

In [19]:
df.loc[null_index,'worldPercentage']=values

In [20]:
df

,place,pop1980,pop2000,pop2010,pop2022,pop2023,pop2025,pop2030,pop2050,country,area,landAreaKm,cca2,cca3,netChange,growthRate,worldPercentage,density,densityMi,rank
0,356,696828385.0,1.059634e+09,1.240614e+09,1.417173e+09,1.428628e+09,1.451771e+09,1.514994e+09,1.670491e+09,India,3287590.00,2973190.00,IN,IND,0.4184,0.0081,1.785000e-01,480.5033,1244.5036,1
1,156,982372466.0,1.264099e+09,1.348191e+09,1.425887e+09,1.425671e+09,1.425101e+09,1.415606e+09,1.312636e+09,China,9706961.00,9424702.90,CN,CHN,-0.0113,-0.0002,1.781000e-01,151.2696,391.7884,2
2,840,223140018.0,2.823986e+08,3.111828e+08,3.382899e+08,3.399966e+08,3.433965e+08,3.521623e+08,3.753920e+08,United States,9372610.00,9147420.00,US,USA,0.0581,0.0050,4.250000e-02,37.1686,96.2666,3
3,360,148177096.0,2.140724e+08,2.440162e+08,2.755013e+08,2.775341e+08,2.816416e+08,2.921501e+08,3.172252e+08,Indonesia,1904569.00,1877519.00,ID,IDN,0.0727,0.0074,3.470000e-02,147.8196,382.8528,4
4,586,80624057.0,1.543699e+08,1.944545e+08,2.358249e+08,2.404857e+08,2.500089e+08,2.740298e+08,3.678085e+08,Pakistan,881912.00,770880.00,PK,PAK,0.1495,0.0198,3.000000e-02,311.9625,807.9829,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,500,11452.0,5.138000e+03,4.938000e+03,4.390000e+03,4.386000e+03,4.378105e+03,4.301000e+03,3.781000e+03,Montserrat,102.00,102.00,MS,MSR,NaN,-0.0009,5.452772e-07,43.0000,111.3700,230
230,238,2240.0,3.080000e+03,3.187000e+03,3.780000e+03,3.791000e+03,3.812988e+03,3.869000e+03,3.779000e+03,Falkland Islands,12173.00,12173.00,FK,FLK,NaN,0.0029,4.713055e-07,0.3114,0.8066,231
231,570,3637.0,2.074000e+03,1.812000e+03,1.934000e+03,1.935000e+03,1.936935e+03,1.948000e+03,2.096000e+03,Niue,261.00,261.00,NU,NIU,0.0000,0.0005,2.405635e-07,7.4138,19.2017,232
232,772,1647.0,1.666000e+03,1.367000e+03,1.871000e+03,1.893000e+03,1.937675e+03,2.046000e+03,2.430000e+03,Tokelau,12.00,10.00,TK,TKL,NaN,0.0118,2.353419e-07,189.3000,490.2870,233
233,336,733.0,6.510000e+02,5.960000e+02,5.100000e+02,5.180000e+02,5.342652e+02,5.610000e+02,7.310000e+02,Vatican City,0.44,0.44,VA,VAT,NaN,0.0157,6.439890e-08,1177.2727,3049.1364,234