In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_absolute_error,accuracy_score
from sklearn.datasets import load_breast_cancer

In [2]:
data=load_breast_cancer()

In [3]:
data.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [4]:
df2=pd.DataFrame(data.data,columns=data.feature_names)

In [5]:
df2

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [6]:
df=pd.read_csv("housing (2).csv")

In [7]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity,median_house_value
0,-122.23,37.88,41,880,129.0,322,126,8.3252,NEAR BAY,452600
1,-122.22,37.86,21,7099,1106.0,2401,1138,8.3014,NEAR BAY,358500
2,-122.24,37.85,52,1467,190.0,496,177,7.2574,NEAR BAY,352100
3,-122.25,37.85,52,1274,235.0,558,219,5.6431,NEAR BAY,341300
4,-122.25,37.85,52,1627,280.0,565,259,3.8462,NEAR BAY,342200
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25,1665,374.0,845,330,1.5603,INLAND,78100
20636,-121.21,39.49,18,697,150.0,356,114,2.5568,INLAND,77100
20637,-121.22,39.43,17,2254,485.0,1007,433,1.7000,INLAND,92300
20638,-121.32,39.43,18,1860,409.0,741,349,1.8672,INLAND,84700
20639,-121.24,39.37,16,2785,616.0,1387,530,2.3886,INLAND,89400

In [8]:
df.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
ocean_proximity         0
median_house_value      0
dtype: int64

In [9]:
bd=df["total_bedrooms"].mean()
fbd=df[df["total_bedrooms"].isna()].index
df.loc[fbd,"total_bedrooms"]=bd

In [10]:
df.isna().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
ocean_proximity       0
median_house_value    0
dtype: int64

In [11]:
label=LabelEncoder()

In [12]:

op=label.fit_transform(df.loc[:,["ocean_proximity"]])
df.loc[:,"ocean_proximity"]=op

c:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [13]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity,median_house_value
0,-122.23,37.88,41,880,129.0,322,126,8.3252,3,452600
1,-122.22,37.86,21,7099,1106.0,2401,1138,8.3014,3,358500
2,-122.24,37.85,52,1467,190.0,496,177,7.2574,3,352100
3,-122.25,37.85,52,1274,235.0,558,219,5.6431,3,341300
4,-122.25,37.85,52,1627,280.0,565,259,3.8462,3,342200
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25,1665,374.0,845,330,1.5603,1,78100
20636,-121.21,39.49,18,697,150.0,356,114,2.5568,1,77100
20637,-121.22,39.43,17,2254,485.0,1007,433,1.7000,1,92300
20638,-121.32,39.43,18,1860,409.0,741,349,1.8672,1,84700
20639,-121.24,39.37,16,2785,616.0,1387,530,2.3886,1,89400

In [14]:
sc=StandardScaler()

In [15]:

x=df.drop(columns="median_house_value",axis=1)
y=df["median_house_value"]
sx=sc.fit_transform(x)

In [16]:
xtrain,xtest,ytrain,ytest=train_test_split(sx,y,random_state=39,test_size=0.2)

In [17]:
model=LinearRegression()
model.fit(xtrain,ytrain)

LinearRegression()

In [18]:
pred=model.predict(xtest)
r2_score(ytest,pred)

0.6397923890952333

decision tree

In [19]:
from sklearn.tree import DecisionTreeRegressor

In [20]:
dt=DecisionTreeRegressor(max_depth=10,min_samples_split=60,min_samples_leaf=10,max_features=10,random_state=42)
dt.fit(xtrain,ytrain)

DecisionTreeRegressor(max_depth=10, max_features=10, min_samples_leaf=10,
                      min_samples_split=60, random_state=42)

In [21]:
predi=dt.predict(xtest)

In [22]:
r2_score(ytest,predi)*100

74.37013981096933

In [23]:
from sklearn.ensemble import RandomForestRegressor

In [24]:
rand=RandomForestRegressor(random_state=42,oob_score=True,max_depth=20,min_samples_split=10,warm_start=True,min_samples_leaf=4,n_jobs=True)

In [25]:
rand.fit(xtrain,ytrain)

RandomForestRegressor(max_depth=20, min_samples_leaf=4, min_samples_split=10,
                      n_jobs=True, oob_score=True, random_state=42,
                      warm_start=True)

In [26]:
pre=rand.predict(xtest)

In [27]:
r2_score(ytest,pre)*100

81.88095300714802

In [28]:
from sklearn.ensemble import RandomForestClassifier

In [29]:
again=label.fit_transform(df.loc[:,["ocean_proximity"]])
df.insert(column="newtar",loc=6,value=again)
df.drop(columns="ocean_proximity",axis=1,inplace=True)

c:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [30]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,newtar,households,median_income,median_house_value
0,-122.23,37.88,41,880,129.0,322,3,126,8.3252,452600
1,-122.22,37.86,21,7099,1106.0,2401,3,1138,8.3014,358500
2,-122.24,37.85,52,1467,190.0,496,3,177,7.2574,352100
3,-122.25,37.85,52,1274,235.0,558,3,219,5.6431,341300
4,-122.25,37.85,52,1627,280.0,565,3,259,3.8462,342200
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25,1665,374.0,845,1,330,1.5603,78100
20636,-121.21,39.49,18,697,150.0,356,1,114,2.5568,77100
20637,-121.22,39.43,17,2254,485.0,1007,1,433,1.7000,92300
20638,-121.32,39.43,18,1860,409.0,741,1,349,1.8672,84700
20639,-121.24,39.37,16,2785,616.0,1387,1,530,2.3886,89400

In [31]:
rfc=RandomForestClassifier()
rfc

RandomForestClassifier()

In [32]:
from sklearn.preprocessing import MinMaxScaler

In [33]:
minmax=MinMaxScaler()

In [34]:
# odi=OrdinalEncoder()

In [35]:
bx=df.drop(columns="newtar",axis=1)
by=df.loc[:,'newtar']
sbx=minmax.fit_transform(bx)
XXtrain,XXtest,YYtrain,YYtest=train_test_split(sbx,by,random_state=35,test_size=0.2)

In [36]:
YYtrain

1380     3
12294    1
7387     0
14454    4
2927     1
        ..
19391    1
15393    0
9143     1
17679    0
5833     0
Name: newtar, Length: 16512, dtype: int64

In [37]:
rfc.fit(XXtrain,YYtrain)

RandomForestClassifier()

In [38]:
pr=rfc.predict(xtest)

In [39]:
accuracy_score(ytest,pr)

c:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:98: UserWarning: The number of unique classes is greater than 50% of the number of samples.
  type_true = type_of_target(y_true, input_name="y_true")

0.0

In [49]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

In [45]:
parameters = {
    "n_estimators": [50, 100, 150],
    "max_depth": [3, 5, 7],
    "criterion": ["squared_error", "absolute_error", "friedman_mse"],
    "min_samples_split": [2, 3, 4]
}

grid_search=GridSearchCV(estimator=rand,param_grid=parameters,cv=5,scoring="r2",verbose=1)

In [47]:
grid_search.fit(xtrain,ytrain)
grid_search.best_params_
grid_search.best_score_

Fitting 5 folds for each of 81 candidates, totalling 405 fits

KeyboardInterrupt:

In [51]:
parameters_random={
    'n_estimators':randint(40,150),
    'max_depth':randint(1,15),
    'criterion':["squared_error","absolute_error"],

}

random_search=RandomizedSearchCV(estimator=rand,cv=5,n_iter=15,scoring="r2",verbose=1,param_distributions=parameters_random)

random_search.fit(xtrain,ytrain)

Fitting 5 folds for each of 15 candidates, totalling 75 fits

RandomizedSearchCV(cv=5,
                   estimator=RandomForestRegressor(max_depth=20,
                                                   min_samples_leaf=4,
                                                   min_samples_split=10,
                                                   n_jobs=True, oob_score=True,
                                                   random_state=42,
                                                   warm_start=True),
                   n_iter=15,
                   param_distributions={'criterion': ['squared_error',
                                                      'absolute_error'],
                                        'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000001802BA3A030>,
                                        'n_estimators': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000001802BC250D0>},
                   scoring='r2', verbose=1)