In [1]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [2]:
df= pd.read_csv('heart.csv')
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [3]:
df.target.value_counts()

target
1    526
0    499
Name: count, dtype: int64

In [4]:
# independent , dependent variable
x= df.iloc[:,:-1]
y= df.iloc[:,-1]

In [5]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.25,random_state=50)

In [10]:
dt= DecisionTreeClassifier(max_depth=6, criterion='entropy')  # criterion= 'gini' by default

In [11]:
params={
    'max_depth':7,
    'criterion':'entropy'
}

In [12]:
dt.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=6)

In [13]:
y_pred= dt.predict(x_test)

In [14]:
from sklearn.metrics import classification_report, confusion_matrix, recall_score, precision_score, accuracy_score

In [15]:
accuracy_score(y_test, y_pred)

0.8793774319066148

In [16]:
confusion_matrix(y_test, y_pred)

array([[107,  10],
       [ 21, 119]], dtype=int64)

In [17]:
precision_score(y_test, y_pred)

0.9224806201550387

In [18]:
recall_score(y_test, y_pred)

0.85

In [19]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.91      0.87       117
           1       0.92      0.85      0.88       140

    accuracy                           0.88       257
   macro avg       0.88      0.88      0.88       257
weighted avg       0.88      0.88      0.88       257

In [20]:
dict_report = classification_report(y_test, y_pred, output_dict=True)

In [21]:
dict_report

{'0': {'precision': 0.8359375,
  'recall': 0.9145299145299145,
  'f1-score': 0.8734693877551021,
  'support': 117.0},
 '1': {'precision': 0.9224806201550387,
  'recall': 0.85,
  'f1-score': 0.8847583643122676,
  'support': 140.0},
 'accuracy': 0.8793774319066148,
 'macro avg': {'precision': 0.8792090600775193,
  'recall': 0.8822649572649572,
  'f1-score': 0.8791138760336848,
  'support': 257.0},
 'weighted avg': {'precision': 0.8830816121467137,
  'recall': 0.8793774319066148,
  'f1-score': 0.8796190247901339,
  'support': 257.0}}

In [22]:
# # pip install joblib
# import joblib 
# joblib.dump(dt,'model.pkl')

In [24]:
# Experiment tracking
# pip install mlflow
# mlflow ui - local run krrega 
import mlflow

In [28]:
mlflow.set_experiment('GenAI Batch')
mlflow.set_tracking_uri(uri="http://127.0.0.1:5000/")

with mlflow.start_run(run_name="GenAI"): # run_name
    mlflow.log_params(params)
    mlflow.log_metrics({
        'accuracy':dict_report['accuracy'],
        'recall_score_0':dict_report['0']['recall'],
        'recall_score_1':dict_report['1']['recall'],
        'f1_score':dict_report['macro avg']['f1-score'],
        'precision_macro':dict_report['macro avg']['precision'],
    })
    mlflow.sklearn.log_model(dt,"Decision Tree Modelv2")

2026/01/19 13:58:41 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/01/19 13:58:52 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run GenAI at: http://127.0.0.1:5000/#/experiments/131479339063196540/runs/6bf3390288e546d7a565b8392055fdfa
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/131479339063196540

In [ ]:
model_name="Decision Tree Model"
# run_id= input("Enter run id ")
run_id= "3ef7fe97d2564c1faf5d52e5de83396e"
model_uri=f"runs:/{run_id}/{model_name}"
mlflow.register_model(model_uri, model_name)

Registered model 'Decision Tree Model' already exists. Creating a new version of this model...
2026/01/19 13:58:54 WARNING mlflow.tracking._model_registry.fluent: Run with id 3ef7fe97d2564c1faf5d52e5de83396e has no artifacts at artifact path 'Decision Tree Model', registering model based on models:/m-4940dd8ded0340b597b86de481a96671 instead
2026/01/19 13:58:54 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: Decision Tree Model, version 2
Created version '2' of model 'Decision Tree Model'.

<ModelVersion: aliases=[], creation_timestamp=1768811334757, current_stage='None', deployment_job_state=<ModelVersionDeploymentJobState: current_task_name='', job_id='', job_state='DEPLOYMENT_JOB_CONNECTION_STATE_UNSPECIFIED', run_id='', run_state='DEPLOYMENT_JOB_RUN_STATE_UNSPECIFIED'>, description='', last_updated_timestamp=1768811334757, metrics=None, model_id=None, name='Decision Tree Model', params=None, run_id='3ef7fe97d2564c1faf5d52e5de83396e', run_link='', source='models:/m-4940dd8ded0340b597b86de481a96671', status='READY', status_message=None, tags={}, user_id='', version='2'>

In [30]:
x_test

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
365,53,1,2,130,246,1,0,173,0,0.0,2,3,2
737,67,1,0,120,229,0,0,129,1,2.6,1,2,3
10,71,0,0,112,149,0,1,125,0,1.6,1,0,2
957,50,1,2,140,233,0,1,163,0,0.6,1,1,3
328,70,1,0,130,322,0,0,109,0,2.4,1,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
891,64,0,0,180,325,0,1,154,1,0.0,2,0,2
368,58,1,2,105,240,0,0,154,1,0.6,1,0,3
339,60,1,0,130,253,0,1,144,1,1.4,2,1,3
126,66,1,0,120,302,0,0,151,0,0.4,1,0,2
213,43,1,2,130,315,0,1,162,0,1.9,2,1,2

In [30]:
# use -load model
model_name="Decision Tree Model"
model_version=2
model_uri=f"models:/{model_name}/{model_version}"
loaded_model= mlflow.sklearn.load_model(model_uri)
y= loaded_model.predict(x_test)
y

array([1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1], dtype=int64)

In [ ]:
x_test[:1]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
365,53,1,2,130,246,1,0,173,0,0.0,2,3,2